server:
  port: 8080
  servlet:
    context-path: /mvc


spring:
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
    application:
      name:mvc
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&characterEncoding=utf-8&allowPublicKeyRetrieval=true
      username: root
      password: mysql
      driver-class-name: com.mysql.jdbc.Driver
      #type: com.mysql.cj.jdbc.MysqlConnectionPoolDataSource
      #repository: com.train.demo1.dao.user.repository
      #entity: com.train.demo1.dao.user.entity
      # 使用druid数据源
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    redis:
      host: localhost
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
    jpa:
      show-sql: true

